<?php
/**
 * Convert the MySQL dump's INSERT rows into a SQLite-loadable seed file.
 *
 * The schema itself comes from the migrations (already verified), so this only
 * extracts data. MySQL-only syntax is rewritten and tables that Laravel or a
 * package owns are skipped.
 *
 * Usage: php import_dump.php <dump.sql> <out.sql>
 */
$dump = $argv[1];
$out  = $argv[2];

$skip = array(
    'migrations',                     // Laravel's own bookkeeping
    'oauth_access_tokens', 'oauth_auth_codes', 'oauth_clients',
    'oauth_personal_access_clients', 'oauth_refresh_tokens',
    'personal_access_tokens',         // tokens are re-issued at login
    'failed_jobs', 'password_resets',
);

$fh = fopen($dump, 'r');
if (!$fh) { fwrite(STDERR, "cannot open $dump\n"); exit(1); }

$buf = '';
$stmts = array();
$counts = array();

while (($line = fgets($fh)) !== false) {
    if ($buf === '' && strpos($line, 'INSERT INTO `') !== 0) continue;
    $buf .= $line;

    // A statement ends on a line terminating with ");"
    if (!preg_match('/\);\s*$/', rtrim($line))) continue;

    $stmt = $buf;
    $buf  = '';

    if (!preg_match('/^INSERT INTO `([^`]+)`/', $stmt, $m)) continue;
    $table = $m[1];
    if (in_array($table, $skip, true)) continue;

    // MySQL escapes a quote as \' ; SQLite wants ''.
    // Walk the string so we only touch escapes inside string literals.
    $s = $stmt; $o = ''; $len = strlen($s); $in = false;
    for ($i = 0; $i < $len; $i++) {
        $c = $s[$i];
        if (!$in) {
            if ($c === "'") { $in = true; $o .= $c; continue; }
            $o .= $c; continue;
        }
        // inside a single-quoted literal
        if ($c === "\\" && $i + 1 < $len) {
            $n = $s[$i + 1];
            if ($n === "'")      { $o .= "''"; $i++; continue; }
            if ($n === '"')      { $o .= '"';  $i++; continue; }
            if ($n === "\\")     { $o .= "\\"; $i++; continue; }
            if ($n === 'n')      { $o .= "\n"; $i++; continue; }
            if ($n === 'r')      { $o .= "\r"; $i++; continue; }
            if ($n === '0')      { $o .= '';   $i++; continue; }
            $o .= $n; $i++; continue;
        }
        if ($c === "'") {
            // doubled '' inside a literal stays escaped
            if ($i + 1 < $len && $s[$i + 1] === "'") { $o .= "''"; $i++; continue; }
            $in = false; $o .= $c; continue;
        }
        $o .= $c;
    }
    $stmt = $o;

    // MySQL zero dates are not valid in SQLite comparisons.
    $stmt = str_replace("'0000-00-00 00:00:00'", "NULL", $stmt);
    $stmt = str_replace("'0000-00-00'", "NULL", $stmt);

    $stmts[] = rtrim($stmt);
    if (!isset($counts[$table])) $counts[$table] = 0;
    $counts[$table] += substr_count($stmt, '),(') + 1;
}
fclose($fh);

$header = "-- Data extracted from the production dump for local API testing.\n"
        . "-- Generated by tools/testdb/import_dump.php - do not edit by hand.\n"
        . "PRAGMA foreign_keys=OFF;\nBEGIN;\n";
$footer = "COMMIT;\n";

file_put_contents($out, $header . implode("\n", $stmts) . "\n" . $footer);

ksort($counts);
$total = 0;
foreach ($counts as $t => $c) { $total += $c; }
echo count($stmts) . " statements, ~$total rows across " . count($counts) . " tables\n";
foreach ($counts as $t => $c) printf("  %-34s %5d\n", $t, $c);
